spring.application.name=Assignment
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Java05_ASM;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=mipipo123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ? Khai báo file ngôn ng?
spring.messages.basename=layout
spring.messages.encoding=UTF-8

# ? Thi?t l?p ngôn ng? m?c ??nh là ti?ng Vi?t
spring.web.locale=vi
spring.web.locale-resolver=fixed

spring.security.oauth2.client.registration.google.client-id=116453815828-ur60o316c51ulb8mkdjn229eqev9527a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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